name: Build Multi Scanner FAP

on:
  push:
    branches: [ main ]  # Compile à chaque push sur main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Clone Flipper Firmware
      run: |
        git clone https://github.com/flipperdevices/flipperzero-firmware.git
        cd flipperzero-firmware
        pip3 install -r requirements.txt

    - name: Compile Multi Scanner
      run: |
        cd flipperzero-firmware
        ../fbt fap_multi_scanner  # Nom de l’app dans fbt